FROM ubuntu:16.04

RUN apt-get update

RUN apt-get install -y software-properties-common

RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php

RUN apt-get update

RUN ["apt-get", "install", "-y", "-f", "php7.1", "php7.1-fpm", "nginx", "supervisor", "php7.1-pdo-mysql", "php7.1-mbstring", "php7.1-curl", "php7.1-xml"]

RUN ["apt-get", "install", "-y", "vim"]

CMD service supervisor start && service php7.1-fpm start && nginx -g 'daemon off;'